apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: local-operator-group
  namespace: local-storage
  spec:
    targetNamespaces:
    - local-storage

---

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: local-storage-manifests
  namespace: local-storage
spec:
  sourceType: grpc
  image: quay.io/gnufied/local-registry:v4.2.0

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-subscription
  namespace: local-storage
spec:
  channel: stable
  name: local-storage-operator
  source: local-storage-manifests
  sourceNamespace: local-storage
