apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: localstorageproviders.local.storage.openshift.io
spec:
  group: local.storage.openshift.io
  names:
    kind: LocalStorageProvider
    listKind: LocalStorageProviderList
    plural: localstorageproviders
    singular: localstorageprovider
  scope: Namespaced
  version: v1alpha1
