apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: local-storage-operator.v4.2.0
  namespace: placeholder
  labels:
    operator-metering: "true"
spec:
  displayName: Local Storage
  description: Local Storage Operator
  keywords: [local storage]
  version: 4.2.0
  maturity: stable
  maintainers:
    - email: aos-storage-staff@redhat.com
      name: Red Hat
  provider:
    name: Red Hat
  labels:
    alm-owner-metering: local-storage-operator
    alm-status-descriptors: local-storage-operator.v4.2.0
  selector:
    matchLabels:
      alm-owner-metering: local-storage-operator
  installModes:
  - type: OwnNamespace
    supported: false
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      permissions:
        - rules:
          - apiGroups:
            - local.storage.openshift.io
            resources:
            - "*"
            verbs:
            - "*"
          - apiGroups:
            - ""
            resources:
            - pods
            - services
            - endpoints
            - persistentvolumeclaims
            - events
            - configmaps
            - secrets
            verbs:
            - "*"
          - apiGroups:
            - apps
            resources:
            - deployments
            - daemonsets
            - replicasets
            - statefulsets
            verbs:
            - "*"
          serviceAccountName: local-storage-operator
      clusterPermissions:
        - rules:
          - apiGroups:
            - storage.k8s.io
            resources:
            - storageclasses
            verbs:
            - "*"
          - apiGroups:
            - rbac.authorization.k8s.io
            resources:
            - clusterroles
            - clusterrolebindings
            - rolebindings
            verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
          - apiGroups:
            - ""
            resources:
            - serviceaccounts
            verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
          - apiGroups:
            - ""
            resources:
            - nodes
            verbs:
            - get
          - apiGroups:
            - ""
            resources:
            - persistentvolumes
            verbs:
            - get
            - list
            - watch
            - create
            - delete
          serviceAccountName: local-storage-operator
        - rules:
          - apiGroups:
            - security.openshift.io
            resources:
            - securitycontextconstraints
            verbs:
            - use
            resourceNames:
            - privileged
          serviceAccountName: local-storage-admin
      deployments:
        - name: local-storage-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: local-storage-operator
            template:
              metadata:
                labels:
                  name: local-storage-operator
              spec:
                serviceAccountName: local-storage-operator
                containers:
                  - name: local-storage-operator
                    image: quay.io/openshift/origin-local-storage-operator:latest
                    ports:
                    - containerPort: 60000
                      name: metrics
                    command:
                    - local-storage-operator
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: OPERATOR_NAME
                        value: "local-storage-operator"
                      - name: PROVISIONER_IMAGE
                        value: quay.io/openshift/origin-local-storage-static-provisioner:latest
                      - name: DISKMAKER_IMAGE
                        value: quay.io/openshift/origin-local-storage-diskmaker:latest
  customresourcedefinitions:
    owned:
      - displayName: Local Volume operator
        group: local.storage.openshift.io
        kind: LocalVolume
        name: localvolumes.local.storage.openshift.io
        description: Manage local storage volumes for Openshift
        version: v1
        specDescriptors:
          - description: Management state of operator
            displayName: Managementstate
            path: managementState
          - description: Log level of operator
            displayName: LogLevel
            path: logLevel
          - description: Selected nodes for local storage
            displayName: NodeSelector
            path: nodeSelector
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:selector'
          - description: StorageClass devices configured by the operator
            displayName: StorageClassDevices
            path: storageClassDevices
        statusDescriptors:
          - description: Last generation of this object
            displayName: ObservedGeneration
            path: observedGeneration
          - description: Management State of the operator
            displayName: ManagementState
            path: managementState
          - description: Last known condition of the operator
            displayName: Conditions
            path: conditions
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.conditions'
