apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: local-storage-operator.v0.0.2
  namespace: placeholder
  labels:
    operator-metering: "true"
spec:
  displayName: Local Storage
  description: Local Storage... # TODO: description
  keywords: [local storage]
  version: 0.0.2
  maturity: alpha
  maintainers:
    - email: aos-storage-staff@redhat.com
      name: Red Hat
  provider:
    name: Red Hat
  labels:
    alm-owner-metering: local-storage-operator
    alm-status-descriptors: local-storage-operator.v0.0.2
  selector:
    matchLabels:
      alm-owner-metering: local-storage-operator
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      permissions:
        - rules:
          - apiGroups:
            - local.storage.openshift.io
            resources:
            - "*"
            verbs:
            - "*"
          - apiGroups:
            - ""
            resources:
            - pods
            - services
            - endpoints
            - persistentvolumeclaims
            - events
            - configmaps
            - secrets
            verbs:
            - "*"
          - apiGroups:
            - apps
            resources:
            - deployments
            - daemonsets
            - replicasets
            - statefulsets
            verbs:
            - "*"
          serviceAccountName: local-storage-operator
      clusterPermissions:
        - rules:
          - apiGroups:
            - storage.k8s.io
            resources:
            - storageclasses
            verbs:
            - "*"
          - apiGroups:
            - rbac.authorization.k8s.io
            resources:
            - clusterroles
            - clusterrolebindings
            - rolebindings
            verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
          - apiGroups:
            - ""
            resources:
            - serviceaccounts
            verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
          - apiGroups:
            - ""
            resources:
            - nodes
            verbs:
            - get
          serviceAccountName: local-storage-operator
      deployments:
        - name: local-storage-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: local-storage-operator
            template:
              metadata:
                labels:
                  name: local-storage-operator
              spec:
                serviceAccountName: local-storage-operator
                containers:
                  - name: local-storage-operator
                    image: quay.io/gnufied/local-storage-operator:v0.0.9
                    ports:
                    - containerPort: 60000
                      name: metrics
                    command:
                    - local-storage-operator
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: OPERATOR_NAME
                        value: "local-storage-operator"
  customresourcedefinitions:
    owned:
      - displayName: Local Storage Provider
        group: local.storage.openshift.io
        kind: LocalVolume
        name: localvolumes.local.storage.openshift.io
        description: Manage local storage volumes for Openshift
        # TODO: specDescriptors
        # TODO: statusDescriptors
        version: v1alpha1
